# HTTP Server (Tomcat) Port
server: 
  port: 8080
logging.level.org.hibernate.SQL: DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder: TRACE
# Disable Spring Boot's "Whitelabel" default error page, so we can use our own
error:
  whitelabel:
    enabled: true

spring:
   application:
     name: unlimits_gateway
   main:
     allow-bean-definition-overriding: true
   cloud:
    metrics:
      enabled: true
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
              allowedOrigins: "*"
              allowedMethods: "*"
              allowedHeaders: "*"
      routes:
        - id: unlimits_auth
          uri: http://localhost:3333/
          predicates:
            - Path=/auth/**
          filters:
            - RewritePath=/auth/(?<segment>.*), /$\{segment}
        - id: unlimits_content
          uri:  http://localhost:4444/
          predicates:
            - Path=/content/**
          filters:
            - RewritePath=/content/(?<segment>.*), /$\{segment}
      
management:
  endpoints:
    web:
      exposure:
        include: "*"

# Discovery Server Access
eureka:
    client:
      serviceUrl:
        defaultZone: http://localhost:1111/eureka/       